version: '2'
services:
  gateway:
    image: nginx
    ports:
      - 7000:7000
    restart: always
    volumes:
      - ./gateway.nginx:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf

  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 8M
    restart: on-failure

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379
