package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'BuildFront'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("BuildFront")
    name = "Build front"

    artifactRules = "front/dist/* => front.zip"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        script {
            workingDir = "front"
            scriptContent = """
                #!/bin/bash
                set -e -x
                yarn
                #yarn test-ci
                yarn build
                #yarn build-storybook
            """.trimIndent()
            dockerImage = "node:latest"
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
            dockerPull = true
        }
        dockerCommand {
            commandType = build {
                source = path {
                    path = "front/Dockerfile"
                }
                contextDir = "front"
                namesAndTags = "front"
                commandArgs = "--pull"
            }
            param("dockerImage.platform", "linux")
        }
        dockerCommand {
            commandType = push {
                namesAndTags = "snakepit.azurecr.io/front:%build.number%"
            }
        }
    }

    triggers {
        vcs {
            triggerRules = "+:front/**"
            branchFilter = ""
        }
    }
}))

