package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "OAuthProvider"
                id = "PROJECT_EXT_8"
                param("displayName", "Azure DevOps")
                param("serverUrl", "https://snakepit.azurecr.io")
                param("type", "token")
                param("providerType", "tfs")
                param("secure:accessToken", "credentialsJSON:75903c56-3b59-478d-8b28-003042310c70")
            }
        }
    }
}
