package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "OAuthProvider"
                id = "PROJECT_EXT_8"
                param("displayName", "Azure DevOps")
                param("serverUrl", "https://snakepit.azurecr.io")
                param("type", "token")
                param("providerType", "tfs")
                param("secure:accessToken", "credentialsJSON:7ae8d5d6-91cc-4b26-b6ed-33d916de8b2c")
            }
        }
    }
}
